### ISSUE TITLE
sync up env setup scripts with latest mizar

### ISSUE THREAD

**Issue by pdgetrf** [CentaurusInfra/fornax#53]
- [ ] sync up with the latest Mizar runtime (golang)

**Comment by pdgetrf** [comment]
@jshaofuturewei do we have additional task to do for this? if not, we could move this to CLOSED

**Comment by jshaofuturewei** [comment]
> @jshaofuturewei do we have additional task to do for this? if not, we could move this to CLOSED

@pdgetrf We don't have other tasks for it now. Please move it to CLOSED. I have not seen any changes from the Mizar team to update python3.7 to python3.9 yet. But it does matter.

**Comment by pdgetrf** [comment]
> > @jshaofuturewei do we have additional task to do for this? if not, we could move this to CLOSED
> 
> @pdgetrf We don't have other tasks for it now. Please move it to CLOSED. I have not seen any changes from the Mizar team to update python3.7 to python3.9 yet. But it does not matter since the python versions are expected to be consistent.

sounds good!
