### ISSUE TITLE
populate EBPF maps for gateway

### ISSUE THREAD

**Issue by pdgetrf** [CentaurusInfra/fornax#63]
On the agent host, the following info is needed for the transit XDP to work correctly

- Known remote subnets and their VPC id, this is to be added into the *a remote subnet Ebpf map* (Ideally only on the gateway hosts. Might be okay on all hosts as the first implementation)

- Gateway host ip, to be compared with pkt->ip->daddr to determine whether the current host is the gateway

These info are to be passed from the mizar control plane to the Mizar agent on each host and then into Ebpf maps.

The action might need to come from a separate agent controller because Mizar workflow is not aware of the "remote subnets" info. To be discussed.

**Comment by pdgetrf** [comment]
per scrum discussion, description updated about using a separate map to store remote subnet. Note that this map also needs to store the VPC id of the subnet so it should be about the same format as the original network_maps

**Comment by jshaofuturewei** [comment]
A pull request https://github.com/CentaurusInfra/mizar/pull/587 has been created for the mizar team to review.

**Comment by pdgetrf** [comment]
resulted PR https://github.com/CentaurusInfra/mizar/pull/587
